-- MySQL Script generated by MySQL Workbench
-- 02/10/17 02:29:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iman` DEFAULT CHARACTER SET utf8 ;
USE `iman` ;

-- -----------------------------------------------------
-- Table `iman`.`s_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_user` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `bitcoin_address` CHAR(34) NOT NULL,
  `balance` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `debit` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `credit` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `commission_bonus` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `profile_picture_path` VARCHAR(255) NULL DEFAULT NULL,
  `id_card_path` VARCHAR(255) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `is_admin` TINYINT(1) NOT NULL DEFAULT '0',
  `is_manager` TINYINT(1) NOT NULL DEFAULT '0',
  `activated` TINYINT(1) NOT NULL DEFAULT '0',
  `admin_type` INT(11) NULL DEFAULT NULL,
  `activation_id` CHAR(36) NOT NULL,
  `reset_password_id` CHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`b_gh_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`b_gh_transaction` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `s_user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `fk_b_gh_transaction_s_user1_idx` (`s_user_id` ASC),
  CONSTRAINT `fk_b_gh_transaction_s_user1`
    FOREIGN KEY (`s_user_id`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`b_ph_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`b_ph_transaction` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `btc_hash_number_20` CHAR(64) NULL DEFAULT NULL,
  `btc_hash_number_80` CHAR(64) NULL DEFAULT NULL,
  `s_user_id` CHAR(36) NOT NULL,
  `b_gh_transaction_id` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `fk_b_ph_transaction_s_user1_idx` (`s_user_id` ASC),
  INDEX `fk_b_ph_transaction_b_gh_transaction1_idx` (`b_gh_transaction_id` ASC),
  CONSTRAINT `fk_b_ph_transaction_b_gh_transaction1`
    FOREIGN KEY (`b_gh_transaction_id`)
    REFERENCES `iman`.`b_gh_transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_b_ph_transaction_s_user1`
    FOREIGN KEY (`s_user_id`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`b_ewallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`b_ewallet` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `b_ph_transaction_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_b_ewallet_b_ph_transaction1_idx` (`b_ph_transaction_id` ASC),
  CONSTRAINT `fk_b_ewallet_b_ph_transaction1`
    FOREIGN KEY (`b_ph_transaction_id`)
    REFERENCES `iman`.`b_ph_transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`b_manager_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`b_manager_test` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `s_user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_b_manager_test_s_user1_idx` (`s_user_id` ASC),
  CONSTRAINT `fk_b_manager_test_s_user1`
    FOREIGN KEY (`s_user_id`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`b_referral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`b_referral` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `s_user_id` CHAR(36) NOT NULL,
  `s_user_id1` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_b_referral_s_user1_idx` (`s_user_id` ASC),
  INDEX `fk_b_referral_s_user2_idx` (`s_user_id1` ASC),
  CONSTRAINT `fk_b_referral_s_user1`
    FOREIGN KEY (`s_user_id`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_b_referral_s_user2`
    FOREIGN KEY (`s_user_id1`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`b_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`b_task` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner` CHAR(36) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `b_ph_transaction_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_b_task_b_ph_transaction1_idx` (`b_ph_transaction_id` ASC),
  CONSTRAINT `fk_b_task_b_ph_transaction1`
    FOREIGN KEY (`b_ph_transaction_id`)
    REFERENCES `iman`.`b_ph_transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_entity` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_property` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `s_entity_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_s_property_s_entity1_idx` (`s_entity_id` ASC),
  CONSTRAINT `fk_s_property_s_entity1`
    FOREIGN KEY (`s_entity_id`)
    REFERENCES `iman`.`s_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_dropdown`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_dropdown` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `index` INT(11) NOT NULL,
  `s_property_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_s_dropdown_s_property1_idx` (`s_property_id` ASC),
  CONSTRAINT `fk_s_dropdown_s_property1`
    FOREIGN KEY (`s_property_id`)
    REFERENCES `iman`.`s_property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_history` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reference_id` CHAR(36) NOT NULL,
  `old_value` VARCHAR(255) NULL DEFAULT NULL,
  `new_value` VARCHAR(255) NULL DEFAULT NULL,
  `s_property_id` CHAR(36) NOT NULL,
  `s_user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_s_history_s_property1_idx` (`s_property_id` ASC),
  INDEX `fk_s_history_s_user1_idx` (`s_user_id` ASC),
  CONSTRAINT `fk_s_history_s_property1`
    FOREIGN KEY (`s_property_id`)
    REFERENCES `iman`.`s_property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_history_s_user1`
    FOREIGN KEY (`s_user_id`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_outgoing_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_outgoing_email` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Unsent',
  `from` VARCHAR(255) NULL DEFAULT NULL,
  `to` VARCHAR(255) NULL DEFAULT NULL,
  `subject` VARCHAR(255) NULL DEFAULT NULL,
  `body` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_user_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_user_session` (
  `id` CHAR(36) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT '1',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `s_user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `fk_s_user_session_s_user1_idx` (`s_user_id` ASC),
  CONSTRAINT `fk_s_user_session_s_user1`
    FOREIGN KEY (`s_user_id`)
    REFERENCES `iman`.`s_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iman`.`s_workflow_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iman`.`s_workflow_status` (
  `id` CHAR(36) NOT NULL,
  `old_value` VARCHAR(45) NULL DEFAULT NULL,
  `new_value` VARCHAR(45) NULL DEFAULT NULL,
  `index` INT(11) NOT NULL,
  `s_property_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_s_workflow_status_s_property1_idx` (`s_property_id` ASC),
  CONSTRAINT `fk_s_workflow_status_s_property1`
    FOREIGN KEY (`s_property_id`)
    REFERENCES `iman`.`s_property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
